//
//  TransactionResult.swift
//  AdumoPay
//
//  Created by Christopher Smit on 2022/12/10.
//

import Foundation

struct TransactionResponse: Entity {
    /// UID of transaction
    let transactionId: String?

    /// 3DSecure required for transaction or not
    let threeDSecureAuthRequired: Bool

    /// CVV required for transaction or not
    let cvvRequired: Bool?

    /// Error code if error occurred
    let errorCode: String?

    /// Error message if error occurred
    let message: String?

    /// Provider of 3DSecure
    let threeDSecureProvider: String?

    /// URL for POST to Bankserv
    let acsUrl: String?

    /// Generated by Bankserv
    let acsPayload: String?

    /// Generated by Bankserv
    let acsMD: String?

    /// State of the transaction
    let transactionState: String?

    /// UID for created user profile
    let profileUid: String?

    /// Country of issue for the card used
    let cardCountry: String?

    /// Code for currency used in transaction
    let currencyCode: String?

    /// Bankserv ECI flag
    let eciFlag: String?

    /// Bank authorisation code
    let authorisationCode: String?

    /// Bank processor response
    let processorResponse: String?
}
